const ACTION_TYPES = {
 SIGN_IN: 'SIGN_IN',
 SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
 SIGN_IN_ERROR: 'SIGN_IN_ERROR',
 GET_LIST_USER: 'GET_LIST_USER',
 GET_LIST_USER_SUCCESS: 'GET_LIST_USER_SUCCESS',
 GET_LIST_USER_ERROR: 'GET_LIST_USER_ERROR',
 GET_USER_INFOR: 'GET_USER_INFOR',
 GET_USER_INFOR_SUCCESS: 'GET_USER_INFOR_SUCCESS',
 GET_USER_INFOR_ERROR: 'GET_USER_INFOR_ERROR'
};

export default ACTION_TYPES;
